input = "/home/joseluis/Trees/synthetic.ply"
output = "/home/joseluis/groot/synthetic.ggf"
filter_cloud_with_cylinders = false

[normals]
k = 99999
radius = 0.04

[cylinders]
min_points = 10
epsilon = 0.01
sampling = 0.04
normal_deviation = 25.0
overlook_probability = 0.0000001
voxel_size = 0.3

[cylinder_filter]
radius_min = 0.0
radius_max = 0.15
length_min = 0.0
length_max = 999.99

[cluster]
intervals = 60
k = 10