input = "/home/joseluis/Trees/palos.ply"
output = "/home/joseluis/groot/cylinders.ggf"
filter_cloud_with_cylinders = false


[cylinders]
min_points = 200
epsilon = 0.03
sampling = 0.1
normal_deviation = 25.0
overlook_probability = 0.001
voxel_size = 2.5

[cylinder_filter]
radius_min = 0.0
radius_max = 999.0
length_min = 0.0
length_max = 999.99